# Generated by Django 5.0.4 on 2024-04-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Photo',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
