# Generated by Django 5.0.4 on 2024-04-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0004_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.AddField(
            model_name='event',
            name='desc',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='Photo',
            field=models.ImageField(upload_to='pic'),
        ),
    ]
